version: '2'

services:
  openctf:
    build: openctf
    networks:
      - openctf
    ports:
      - 4242:4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./openctf:/openctf

networks:
  openctf:
    driver: bridge